import streamlit as st

st.set_page_config(page_title="AI System Copilot", page_icon="🤖", layout="centered")

st.title("AI Copilot for Enterprise System Understanding")
st.write("Paste a technical artifact below and ask a question about it.")

artifact = st.text_area("Paste code, architecture notes, API documentation, or process notes", height=250)

question = st.text_input("Ask a question", placeholder="Example: Explain what this module does in simple terms")

if st.button("Generate Explanation"):
    if artifact and question:
        st.subheader("AI-style Explanation")
        st.write(
            f"""
            Based on the artifact provided, here is a simplified explanation for the question: **{question}**

            This artifact appears to describe a component in an enterprise workflow. 
            Its likely role is to process a business function, interact with related modules, 
            and support a downstream workflow. For a new engineer, the main things to note are:

            - what the module is responsible for
            - what inputs it consumes
            - which downstream systems may depend on it
            - where a change could have impact

            In the next version, this response would be generated by an LLM using uploaded artifacts.
            """
        )
    else:
        st.warning("Please paste an artifact and enter a question.")
